Repository castcle/castcle-ds-predict, pull requests merged in 2022-01, with the labels that each got.

#74 Temp Lambda
  friend_to_follow.py
  modules/friend_to_follow/friend_to_follow.py
Labels: documentation

#79 Develop to staging
  README.md
  friend_to_follow.py
  modules/coldstart_prediction/coldstart_predictor.py
  modules/friend_to_follow/friend_to_follow.py
  modules/personalized_content/personalize_content_predictor.py
  requirements.txt
  serverless.yml
Labels: documentation, enhancement

#85 add: add timer
  modules/personalized_content/personalize_content_predictor.py
Labels: documentation

#87 fix: collection validator
  modules/personalized_content/personalize_content_predictor.py
Labels: bug

#88 Develop performance
  modules/personalized_content/personalize_content_predictor.py
Labels: documentation

#89 fix: return format and returnCode
  modules/personalized_content/personalize_content_predictor.py
Labels: documentation

#92 Feature/personalize api
  modules/personalized_content/personalize_content_predictor.py
Labels: documentation
