Repository castcle/castcle-ds-predict, pull requests merged in 2022-04, with the labels that each got.

#97 update dateThreshold
  README.md
  coldstart_predictor.py
  modules/coldstart/README.md
  modules/coldstart/__init__.py
  modules/coldstart/coldstart_predictor.py
Labels: documentation

#100 fix dateThreshold
  README.md
  coldstart_predictor.py
  modules/coldstart/README.md
  modules/coldstart/__init__.py
  modules/coldstart/coldstart_predictor.py
  modules/friend_to_follow/friend_to_follow.py
  modules/personalized_content/personalize_content_predictor.py
Labels: documentation

#101 fix feeds dateThreshold to 7days
  README.md
  coldstart_predictor.py
  modules/coldstart/README.md
  modules/coldstart/__init__.py
  modules/coldstart/coldstart_predictor.py
  modules/friend_to_follow/friend_to_follow.py
  modules/personalized_content/personalize_content_predictor.py
Labels: documentation

#103 rename authorId -> author
  modules/coldstart/coldstart_predictor.py
Labels: documentation

#104 add originalPost
  modules/coldstart/coldstart_predictor.py
Labels: documentation

#105 log content_score.shape before iloc:2000
  modules/coldstart/coldstart_predictor.py
Labels: bug

#107 log coldstart content shape
  coldstart_predictor.py
  modules/coldstart/coldstart_predictor.py
Labels: bug

#108 updatedAtThreshold 7.0 -> 30
  coldstart_predictor.py
Labels: documentation

#109 Develop
  coldstart_predictor.py
Labels: documentation

#110 staging -> main below2000
  coldstart_predictor.py
  modules/coldstart/coldstart_predictor.py
Labels: bug, documentation
